---
- name: "Check if docker is installed on your worker machine."
  raw: command -v docker
  register: command_docker_worker
  failed_when: false
  changed_when: false
  check_mode: false
  environment: {}

- name: "Failed, if docker is not installed on your worker machine."
  set_fact:
    unmet_requirements: "{{ unmet_requirements + ['Unable to find docker in your worker machine'] }}"
  changed_when: false
  check_mode: false
  environment: {}
  when:
    - command_docker_worker.rc != 0
