---
- name: "remove NVIDIA persistent mode's file"
  command: "rm -rf /etc/docker-prophet"

- name: uninstall packages
  apt:
    name: nvidia-container-runtime
    state: absent
    update_cache: yes
  when:
    - uninstall_run_time
